#!/bin/bash

sep=10
int=$sep
thread=2400
batch=7
batchsep=4
model=bert
batchsize=8
if false
then
while(($batch<=$batchsize))
do
    while(( $int<=100 ))
    do
        sleep 1
        echo set_active_thread_percentage $thread $int | nvidia-cuda-mps-control
        sleep 1
        trtexec --loadEngine="$model"_1_1_64.engine --duration=10 --shapes=input_ids:"$batch"x128,attention_mask:"$batch"x128,token_type:"$batch"x128 --exportTimes=data/durtime_"$model"_b"$batch"_t$int 
        #trtexec --loadEngine="$model"_1_1_64.engine --duration=10 --shapes=actual_input_1:"$batch"x3x224x224 --exportTimes=data/durtime_"$model"_b"$batch"_t$int 
    #./conperf 1
    #nsys profile -t cuda -s none --export=sqlite --force-overwrite=true -o data/v100_yolv3_t$int ./conperf 1
    #python3 sepper.py data/v100_yolv3_t$int.sqlite 151
        let int+=$sep
    done
    int=10
    let batch+=$batchsep
done
fi
int=$sep
batch=7
while(( $batch<=$batchsize ))
do
    while(( $int<=100 ))
    do
        python3 trtexecps.py data/durtime_"$model"_b"$batch"_t$int
        let int+=$sep
    done
    int=10
    let batch+=$batchsep
done
