#!/bin/bash
int=1
model=vgg19_1_1_64.engine
shape=1
while(($int<=$1))
do
    let int++
    trtexec --loadEngine=$model --avgRuns=50 --duration=10 --shapes=actual_input_1:"$shape"x3x224x224 &
    #sleep 1
   # python3 onnx_to_tensorrt.py &
done
wait
