#!/bin/bash
#alexnet vgg19
model1=vgg19
model2=alexnet
batch1=3
batch2=2
thread1=50
thread2=50
sleep 1
echo set_active_thread_percentage 4483 $thread1 | nvidia-cuda-mps-control
sleep 1
trtexec --loadEngine="$model1"_1_1_64.engine --shapes=actual_input_1:"$batch1"x3x224x224 --duration=30 --exportTimes=data/durtime_"$model1"b"batch1"_"$model2"b"batch2"  &
#trtexec --loadEngine=alexnet_1_1_64.engine --shapes=actual_input_1:1x3x224x224 --duration=10 &
sleep 1
echo set_active_thread_percentage 4483 $thread2 | nvidia-cuda-mps-control
sleep 1
trtexec --loadEngine="$model2"_1_1_64.engine --shapes=actual_input_1:"$batch2"x3x224x224 --duration=30 --exportTimes=data/durtime_"$model2"b"batch2"_"$model1"b"batch1"
wait

python3 trtexecps.py data/durtime_"$model1"b"batch1"_"$model2"b"batch2"
python3 trtexecps.py data/durtime_"$model2"b"batch2"_"$model1"b"batch1"
