#!/bin/bash

sep=10
if true
then
int=$sep
batch=1
model=resnet50
mpsid=5566
while(( $int<=100 ))
do
    sleep 1
    echo set_active_thread_percentage $mpsid $int | nvidia-cuda-mps-control
    sleep 1
    trtexec --loadEngine="$model"_1_1_64.engine --duration=10 --shapes=actual_input_1:"$batch"x3x224x224 --exportTimes=data/durtime_"$model"_b"$batch"_t$int 
    #./conperf 1
    #nsys profile -t cuda -s none --export=sqlite --force-overwrite=true -o data/v100_yolv3_t$int ./conperf 1
    #python3 sepper.py data/v100_yolv3_t$int.sqlite 151
    let int+=$sep

done
fi
int=$sep
while(( $int<=100 ))
do
    python3 trtexecps.py data/durtime_"$model"_b"$batch"_t$int
    let int+=$sep
done
