#!/bin/bash
#alexnet vgg19
model1=vgg19
model2=alexnet
model3=resnet50
batch1=2
batch2=1
batch3=1
thread1=35
thread2=35
thread3=30
mps=2389
sleep 1
echo set_active_thread_percentage $mps $thread1 | nvidia-cuda-mps-control
sleep 1
trtexec --loadEngine="$model1"_1_1_64.engine --shapes=actual_input_1:"$batch1"x3x224x224 --duration=30 --exportTimes=data/durtime_"$model1"b"batch1"_"$model2"b"batch2"_"$model3"b"batch3"  &
#trtexec --loadEngine=alexnet_1_1_64.engine --shapes=actual_input_1:1x3x224x224 --duration=10 &
sleep 1
echo set_active_thread_percentage $mps $thread2 | nvidia-cuda-mps-control
sleep 1
trtexec --loadEngine="$model2"_1_1_64.engine --shapes=actual_input_1:"$batch2"x3x224x224 --duration=30 --exportTimes=data/durtime_"$model2"b"batch2"_"$model1"b"batch1"_"$model3"b"batch3" &
sleep 1
echo set_active_thread_percentage $mps $thread3 | nvidia-cuda-mps-control
sleep 1
trtexec --loadEngine="$model3"_1_1_64.engine --shapes=actual_input_1:"$batch2"x3x224x224 --duration=30 --exportTimes=data/durtime_"$model3"b"batch3"_"$model1"b"batch1"_"$model2"b"batch2"
wait

python3 trtexecps.py data/durtime_"$model1"b"batch1"_"$model2"b"batch2"_"$model3"b"batch3"
python3 trtexecps.py data/durtime_"$model2"b"batch2"_"$model1"b"batch1"_"$model3"b"batch3"
python3 trtexecps.py  data/durtime_"$model3"b"batch3"_"$model1"b"batch1"_"$model2"b"batch2"
