#!/bin/bash

# warm triton server

/workspace/myclient/switch_perf_analyzer $1 $2 $3 $4 $5 $6 -r 1 > warm_log.txt 2>&1
echo $1 $2 $3 $4 $5 $6
echo $*

/workspace/myclient/switch_perf_analyzer $* > log.txt 2>&1
