#!/bin/bash


sep=1
mpsid=$MPSID
model=$1
engine=../"$model"_1_1_64.engine
a=2

nvidia-smi dmon -f data/dmon_"$model"_c"$a" &
smi_pid=$!

if true
then
nsys profile -t cuda -s none --export=sqlite --force-overwrite=true -o data/v100_"$model"_t20_c$a ./conperf $a $model  
    
fi

python3 sepper.py data/v100_"$model"_t20_c$a.sqlite $model $a

sleep 1
kill $smi_pid
sleep 1
python3 nvidiadmonps.py data/dmon_"$model"_c"$a" $model
